[WIP] engine-jupyter
src-d/charts pull request #40
Opened 2018-04-05 16:05 UTC by smola

* Updates old spark-api-jupyter to the new engine-jupyter.

Signed-off-by: Santiago M. Mola <santi@mola.io>

2018-04-17 09:03 UTC, rporres reviewed
This chart was written to be deployed in GCE when we were trying a first approach for the engine playground, that's why it had certain volume assumptions. I finally had to use a different approach. Great that it's been useful anyway.

A few comments:

* bblfsh driver installation is tricky if you want to do it correctly. I've posted some suggestions, but we can leave them for a further version if it is out of the scope (as long as we have some TODO in the code)

* If you want to store your notebooks you can use a hostPath (with a mandatory nodeSelector) or a PersistentVolumeClaim. Unfortunately local PVC are only beta in k8s 1.10 so the most general way to code this would be giving both chances

2018-04-17 09:03 UTC, rporres commented on engine-jupyter/templates/deployment.yaml
> +          args: ["-c", "bblfshd & pid=$! ; sleep 1 && bblfshctl driver install --recommended && kill $pid && exec bblfshd"]
This also has another problem. If you have multiple pods and one gets restarted you could end up with pods with different driver versions

2018-04-17 09:03 UTC, rporres commented on engine-jupyter/values.yaml
> +  resources: {}
nit: missing newline at end of file

2018-04-17 10:39 UTC, smola commented on engine-jupyter/templates/deployment.yaml
> +          args: ["-c", "bblfshd & pid=$! ; sleep 1 && bblfshctl driver install --recommended && kill $pid && exec bblfshd"]
Changed. Copied what bblfshd chart has.

2018-04-18 10:43 UTC, rporres requested changes
I'd rather add persistence as an option. Suggested syntax (untested, though)

2018-04-18 10:43 UTC, rporres commented on engine-jupyter/templates/deployment.yaml
> +        - name: notebooks-dir
I'd give this as an option as it limits how this is deployed. And it closes the door to use this with persistent volume claims which is the standard way of describing volumes in k8s. I'd write something like:

```
# TODO: Add PVC support
{{- if .Values.notebooks.volumes }}
  volumes:
    - name: notebooks-dir
  {{- if .Values.notebooks.volumes.hostPath }}
      hostPath:
        path: {{ .Values.notebooks.volumes.hostPath }}
  {{- end }}
{{- end }}

2018-04-18 10:43 UTC, rporres commented on engine-jupyter/templates/deployment.yaml
> +          volumeMounts:
As comented above, I'd give the opportunity of not saving state if no volume is given and add the same condition:

```
{{- if .Values.notebooks.volumes }}
```

2018-04-18 10:43 UTC, rporres commented on engine-jupyter/values.yaml
> +  hostPath:
To be consistent with the above suggestion, I'd organize this as follows

```
notebooks:
  volumes: {}
    # hostPath: /data-a/notebooks
```

2018-04-23 16:13 UTC, rporres requested changes
There are a few `{{ if ...` and `{{ end  }}` that create unnecessary empty lines

2018-04-23 16:13 UTC, rporres commented on engine-jupyter/templates/deployment.yaml
> +        {{ if .Values.notebooks.volumes }}
nit: please use `{{- if` to avoid new lines

2019-11-18 17:19 UTC, smola commented
Closing, too outdated now.

2019-11-18 17:19 UTC, closed without merging